version: "3.5"

services:
  dc:
    container_name: dc
    image: dc:1.0
    build: .
    volumes:
      - .:/code/
    environment:
      - TEST=test
    entrypoint: sh -c "tail -f /dev/null"
  # localstack:
    # See https://github.com/localstack/localstack/blob/master/docker-compose.yml
    # container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    # image: localstack/localstack
    # privileged: true
    # network_mode: bridge
    # hostname: localstack
    # ports:
      # - "127.0.0.1:53:53"
      # - "127.0.0.1:53:53/udp"
      # - "127.0.0.1:443:443"
      # - "127.0.0.1:4510-4530:4510-4530"
      # - "127.0.0.1:4566:4566"
      # - "127.0.0.1:4571:4571"
    # environment:
      # - AWS_DEFAULT_REGION=us-east-1
      # - SERVICES=dynamodb,s3
      # - DEBUG=${DEBUG-true}
      # - PORT_WEB_UI=${PORT_WEB_UI- }
      # - DOCKER_HOST=unix:///var/run/docker.sock
      # - HOST_TMP_FOLDER=${TMPDIR}
      # - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY- }
      # - HOSTNAME_EXTERNAL=localstack
    # volumes:
      # - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      # - "/var/run/docker.sock:/var/run/docker.sock"
      # - "./scripts:/docker-entrypoint-initaws.d"
      # - "./data:/data"