expected_payload = [
   {
      "resourceType":"Domain",
      "identifier":{
         "name":"enterprise-weather-data-product-api-sbx",
         "community":{
            "name":"APIs"
         }
      },
      "type":{
         "name":"Physical Data Dictionary"
      }
   },
   {
      "resourceType":"Asset",
      "identifier":{
         "name":"enterprise-weather-data-product-api-sbx",
         "domain":{
            "name":"enterprise-weather-data-product-api-sbx",
            "community":{
               "name":"APIs"
            }
         }
      },
      "attributes":{
         "Description":[
            {
               "value":"Proxy gateway to handle weather_data_api lambda requests"
            }
         ],
         "URL":[
            {
               "value":"https://enterprise-weather-data-product-api-sbx.duke-energy.app"
            }
         ]
      },
      "type":{
         "name":"API"
      },
      "relations":{
         "00000000-0000-0000-0000-000000007005:SOURCE":[
            {
               "name":"GET /data/forecasts/_search",
               "domain":{
                  "name":"enterprise-weather-data-product-api-sbx",
                  "community":{
                     "name":"APIs"
                  }
               }
            },
            {
               "name":"GET /weather/forecasts/_search",
               "domain":{
                  "name":"enterprise-weather-data-product-api-sbx",
                  "community":{
                     "name":"APIs"
                  }
               }
            },
            {
               "name":"GET /docs/json",
               "domain":{
                  "name":"enterprise-weather-data-product-api-sbx",
                  "community":{
                     "name":"APIs"
                  }
               }
            },
            {
               "name":"GET /weather/forecast",
               "domain":{
                  "name":"enterprise-weather-data-product-api-sbx",
                  "community":{
                     "name":"APIs"
                  }
               }
            },
            {
               "name":"GET /weather/actuals",
               "domain":{
                  "name":"enterprise-weather-data-product-api-sbx",
                  "community":{
                     "name":"APIs"
                  }
               }
            },
            {
               "name":"GET /weather/forecast/by_station",
               "domain":{
                  "name":"enterprise-weather-data-product-api-sbx",
                  "community":{
                     "name":"APIs"
                  }
               }
            },
            {
               "name":"GET /data/forecast",
               "domain":{
                  "name":"enterprise-weather-data-product-api-sbx",
                  "community":{
                     "name":"APIs"
                  }
               }
            },
            {
               "name":"GET /test",
               "domain":{
                  "name":"enterprise-weather-data-product-api-sbx",
                  "community":{
                     "name":"APIs"
                  }
               }
            },
            {
               "name":"GET /docs/{proxy}",
               "domain":{
                  "name":"enterprise-weather-data-product-api-sbx",
                  "community":{
                     "name":"APIs"
                  }
               }
            },
            {
               "name":"GET /docs",
               "domain":{
                  "name":"enterprise-weather-data-product-api-sbx",
                  "community":{
                     "name":"APIs"
                  }
               }
            }
         ]
      }
   },
   {
      "resourceType":"Asset",
      "identifier":{
         "name":"GET /data/forecasts/_search",
         "domain":{
            "name":"enterprise-weather-data-product-api-sbx",
            "community":{
               "name":"APIs"
            }
         }
      },
      "type":{
         "name":"API Endpoint"
      },
      "relations":{
         "00000000-0000-0000-0000-000000007005:TARGET":[
            {
               "name":"enterprise-weather-data-product-api-sbx",
               "domain":{
                  "name":"enterprise-weather-data-product-api-sbx",
                  "community":{
                     "name":"APIs"
                  }
               }
            }
         ],
         "018da964-d53a-7b18-a8c8-044dbd47a622:TARGET":[
            {
               "name":"v1FindWeatherForecastData",
               "domain":{
                  "name":"enterprise-weather-data-product-api-sbx",
                  "community":{
                     "name":"APIs"
                  }
               }
            }
         ]
      }
   },
   {
      "resourceType":"Asset",
      "displayName":"models",
      "identifier":{
         "name":"v1FindWeatherForecastData > models",
         "domain":{
            "name":"enterprise-weather-data-product-api-sbx",
            "community":{
               "name":"APIs"
            }
         }
      },
      "type":{
         "name":"Column"
      },
      "attributes":{
         "Data Type":[
            {
               "value":"array"
            }
         ]
      },
      "relations":{
         "00000000-0000-0000-0000-000000007042:TARGET":[
            {
               "name":"v1FindWeatherForecastData",
               "domain":{
                  "name":"enterprise-weather-data-product-api-sbx",
                  "community":{
                     "name":"APIs"
                  }
               }
            }
         ]
      }
   },
   {
      "resourceType":"Asset",
      "identifier":{
         "name":"v1FindWeatherForecastData",
         "domain":{
            "name":"enterprise-weather-data-product-api-sbx",
            "community":{
               "name":"APIs"
            }
         }
      },
      "type":{
         "name":"Table"
      },
      "relations":{
         "018da964-d53a-7b18-a8c8-044dbd47a622:SOURCE":[
            {
               "name":"GET /data/forecasts/_search",
               "domain":{
                  "name":"enterprise-weather-data-product-api-sbx",
                  "community":{
                     "name":"APIs"
                  }
               }
            }
         ],
         "00000000-0000-0000-0000-000000007042:SOURCE":[
            {
               "name":"v1FindWeatherForecastData > models",
               "domain":{
                  "name":"enterprise-weather-data-product-api-sbx",
                  "community":{
                     "name":"APIs"
                  }
               }
            }
         ]
      }
   },
   {
      "resourceType":"Asset",
      "identifier":{
         "name":"GET /weather/forecasts/_search",
         "domain":{
            "name":"enterprise-weather-data-product-api-sbx",
            "community":{
               "name":"APIs"
            }
         }
      },
      "type":{
         "name":"API Endpoint"
      },
      "relations":{
         "00000000-0000-0000-0000-000000007005:TARGET":[
            {
               "name":"enterprise-weather-data-product-api-sbx",
               "domain":{
                  "name":"enterprise-weather-data-product-api-sbx",
                  "community":{
                     "name":"APIs"
                  }
               }
            }
         ],
         "018da964-d53a-7b18-a8c8-044dbd47a622:TARGET":[
            {
               "name":"v1FindWeatherForecastData",
               "domain":{
                  "name":"enterprise-weather-data-product-api-sbx",
                  "community":{
                     "name":"APIs"
                  }
               }
            }
         ]
      }
   },
   {
      "resourceType":"Asset",
      "displayName":"models",
      "identifier":{
         "name":"v1FindWeatherForecastData > models",
         "domain":{
            "name":"enterprise-weather-data-product-api-sbx",
            "community":{
               "name":"APIs"
            }
         }
      },
      "type":{
         "name":"Column"
      },
      "attributes":{
         "Data Type":[
            {
               "value":"array"
            }
         ]
      },
      "relations":{
         "00000000-0000-0000-0000-000000007042:TARGET":[
            {
               "name":"v1FindWeatherForecastData",
               "domain":{
                  "name":"enterprise-weather-data-product-api-sbx",
                  "community":{
                     "name":"APIs"
                  }
               }
            }
         ]
      }
   },
   {
      "resourceType":"Asset",
      "identifier":{
         "name":"v1FindWeatherForecastData",
         "domain":{
            "name":"enterprise-weather-data-product-api-sbx",
            "community":{
               "name":"APIs"
            }
         }
      },
      "type":{
         "name":"Table"
      },
      "relations":{
         "018da964-d53a-7b18-a8c8-044dbd47a622:SOURCE":[
            {
               "name":"GET /weather/forecasts/_search",
               "domain":{
                  "name":"enterprise-weather-data-product-api-sbx",
                  "community":{
                     "name":"APIs"
                  }
               }
            }
         ],
         "00000000-0000-0000-0000-000000007042:SOURCE":[
            {
               "name":"v1FindWeatherForecastData > models",
               "domain":{
                  "name":"enterprise-weather-data-product-api-sbx",
                  "community":{
                     "name":"APIs"
                  }
               }
            }
         ]
      }
   },
   {
      "resourceType":"Asset",
      "identifier":{
         "name":"GET /docs/json",
         "domain":{
            "name":"enterprise-weather-data-product-api-sbx",
            "community":{
               "name":"APIs"
            }
         }
      },
      "type":{
         "name":"API Endpoint"
      },
      "relations":{
         "00000000-0000-0000-0000-000000007005:TARGET":[
            {
               "name":"enterprise-weather-data-product-api-sbx",
               "domain":{
                  "name":"enterprise-weather-data-product-api-sbx",
                  "community":{
                     "name":"APIs"
                  }
               }
            }
         ],
         "018da964-d53a-7b18-a8c8-044dbd47a622:TARGET":[
            {
               "name":"empty",
               "domain":{
                  "name":"enterprise-weather-data-product-api-sbx",
                  "community":{
                     "name":"APIs"
                  }
               }
            }
         ]
      }
   },
   {
      "resourceType":"Asset",
      "identifier":{
         "name":"empty",
         "domain":{
            "name":"enterprise-weather-data-product-api-sbx",
            "community":{
               "name":"APIs"
            }
         }
      },
      "type":{
         "name":"Table"
      },
      "relations":{
         "018da964-d53a-7b18-a8c8-044dbd47a622:SOURCE":[
            {
               "name":"GET /docs/json",
               "domain":{
                  "name":"enterprise-weather-data-product-api-sbx",
                  "community":{
                     "name":"APIs"
                  }
               }
            }
         ],
         "00000000-0000-0000-0000-000000007042:SOURCE":[
            
         ]
      }
   },
   {
      "resourceType":"Asset",
      "identifier":{
         "name":"GET /weather/forecast",
         "domain":{
            "name":"enterprise-weather-data-product-api-sbx",
            "community":{
               "name":"APIs"
            }
         }
      },
      "type":{
         "name":"API Endpoint"
      },
      "relations":{
         "00000000-0000-0000-0000-000000007005:TARGET":[
            {
               "name":"enterprise-weather-data-product-api-sbx",
               "domain":{
                  "name":"enterprise-weather-data-product-api-sbx",
                  "community":{
                     "name":"APIs"
                  }
               }
            }
         ],
         "018da964-d53a-7b18-a8c8-044dbd47a622:TARGET":[
            {
               "name":"v1GetWeatherForecastData",
               "domain":{
                  "name":"enterprise-weather-data-product-api-sbx",
                  "community":{
                     "name":"APIs"
                  }
               }
            }
         ]
      }
   },
   {
      "resourceType":"Asset",
      "displayName":"inittime",
      "identifier":{
         "name":"v1GetWeatherForecastData > inittime",
         "domain":{
            "name":"enterprise-weather-data-product-api-sbx",
            "community":{
               "name":"APIs"
            }
         }
      },
      "type":{
         "name":"Column"
      },
      "attributes":{
         "Data Type":[
            {
               "value":"string"
            }
         ]
      },
      "relations":{
         "00000000-0000-0000-0000-000000007042:TARGET":[
            {
               "name":"v1GetWeatherForecastData",
               "domain":{
                  "name":"enterprise-weather-data-product-api-sbx",
                  "community":{
                     "name":"APIs"
                  }
               }
            }
         ]
      }
   },
   {
      "resourceType":"Asset",
      "displayName":"provider",
      "identifier":{
         "name":"v1GetWeatherForecastData > provider",
         "domain":{
            "name":"enterprise-weather-data-product-api-sbx",
            "community":{
               "name":"APIs"
            }
         }
      },
      "type":{
         "name":"Column"
      },
      "attributes":{
         "Data Type":[
            {
               "value":"string"
            }
         ]
      },
      "relations":{
         "00000000-0000-0000-0000-000000007042:TARGET":[
            {
               "name":"v1GetWeatherForecastData",
               "domain":{
                  "name":"enterprise-weather-data-product-api-sbx",
                  "community":{
                     "name":"APIs"
                  }
               }
            }
         ]
      }
   },
   {
      "resourceType":"Asset",
      "displayName":"data",
      "identifier":{
         "name":"v1GetWeatherForecastData > data",
         "domain":{
            "name":"enterprise-weather-data-product-api-sbx",
            "community":{
               "name":"APIs"
            }
         }
      },
      "type":{
         "name":"Column"
      },
      "attributes":{
         "Data Type":[
            {
               "value":"array"
            }
         ]
      },
      "relations":{
         "00000000-0000-0000-0000-000000007042:TARGET":[
            {
               "name":"v1GetWeatherForecastData",
               "domain":{
                  "name":"enterprise-weather-data-product-api-sbx",
                  "community":{
                     "name":"APIs"
                  }
               }
            }
         ]
      }
   },
   {
      "resourceType":"Asset",
      "identifier":{
         "name":"v1GetWeatherForecastData",
         "domain":{
            "name":"enterprise-weather-data-product-api-sbx",
            "community":{
               "name":"APIs"
            }
         }
      },
      "type":{
         "name":"Table"
      },
      "relations":{
         "018da964-d53a-7b18-a8c8-044dbd47a622:SOURCE":[
            {
               "name":"GET /weather/forecast",
               "domain":{
                  "name":"enterprise-weather-data-product-api-sbx",
                  "community":{
                     "name":"APIs"
                  }
               }
            }
         ],
         "00000000-0000-0000-0000-000000007042:SOURCE":[
            {
               "name":"v1GetWeatherForecastData > inittime",
               "domain":{
                  "name":"enterprise-weather-data-product-api-sbx",
                  "community":{
                     "name":"APIs"
                  }
               }
            },
            {
               "name":"v1GetWeatherForecastData > provider",
               "domain":{
                  "name":"enterprise-weather-data-product-api-sbx",
                  "community":{
                     "name":"APIs"
                  }
               }
            },
            {
               "name":"v1GetWeatherForecastData > data",
               "domain":{
                  "name":"enterprise-weather-data-product-api-sbx",
                  "community":{
                     "name":"APIs"
                  }
               }
            }
         ]
      }
   },
   {
      "resourceType":"Asset",
      "identifier":{
         "name":"GET /weather/actuals",
         "domain":{
            "name":"enterprise-weather-data-product-api-sbx",
            "community":{
               "name":"APIs"
            }
         }
      },
      "type":{
         "name":"API Endpoint"
      },
      "relations":{
         "00000000-0000-0000-0000-000000007005:TARGET":[
            {
               "name":"enterprise-weather-data-product-api-sbx",
               "domain":{
                  "name":"enterprise-weather-data-product-api-sbx",
                  "community":{
                     "name":"APIs"
                  }
               }
            }
         ],
         "018da964-d53a-7b18-a8c8-044dbd47a622:TARGET":[
            {
               "name":"v1GetWeatherActualsData",
               "domain":{
                  "name":"enterprise-weather-data-product-api-sbx",
                  "community":{
                     "name":"APIs"
                  }
               }
            }
         ]
      }
   },
   {
      "resourceType":"Asset",
      "displayName":"starttime",
      "identifier":{
         "name":"v1GetWeatherActualsData > starttime",
         "domain":{
            "name":"enterprise-weather-data-product-api-sbx",
            "community":{
               "name":"APIs"
            }
         }
      },
      "type":{
         "name":"Column"
      },
      "attributes":{
         "Data Type":[
            {
               "value":"string"
            }
         ]
      },
      "relations":{
         "00000000-0000-0000-0000-000000007042:TARGET":[
            {
               "name":"v1GetWeatherActualsData",
               "domain":{
                  "name":"enterprise-weather-data-product-api-sbx",
                  "community":{
                     "name":"APIs"
                  }
               }
            }
         ]
      }
   },
   {
      "resourceType":"Asset",
      "displayName":"endtime",
      "identifier":{
         "name":"v1GetWeatherActualsData > endtime",
         "domain":{
            "name":"enterprise-weather-data-product-api-sbx",
            "community":{
               "name":"APIs"
            }
         }
      },
      "type":{
         "name":"Column"
      },
      "attributes":{
         "Data Type":[
            {
               "value":"string"
            }
         ]
      },
      "relations":{
         "00000000-0000-0000-0000-000000007042:TARGET":[
            {
               "name":"v1GetWeatherActualsData",
               "domain":{
                  "name":"enterprise-weather-data-product-api-sbx",
                  "community":{
                     "name":"APIs"
                  }
               }
            }
         ]
      }
   },
   {
      "resourceType":"Asset",
      "displayName":"provider",
      "identifier":{
         "name":"v1GetWeatherActualsData > provider",
         "domain":{
            "name":"enterprise-weather-data-product-api-sbx",
            "community":{
               "name":"APIs"
            }
         }
      },
      "type":{
         "name":"Column"
      },
      "attributes":{
         "Data Type":[
            {
               "value":"string"
            }
         ]
      },
      "relations":{
         "00000000-0000-0000-0000-000000007042:TARGET":[
            {
               "name":"v1GetWeatherActualsData",
               "domain":{
                  "name":"enterprise-weather-data-product-api-sbx",
                  "community":{
                     "name":"APIs"
                  }
               }
            }
         ]
      }
   },
   {
      "resourceType":"Asset",
      "displayName":"location",
      "identifier":{
         "name":"v1GetWeatherActualsData > location",
         "domain":{
            "name":"enterprise-weather-data-product-api-sbx",
            "community":{
               "name":"APIs"
            }
         }
      },
      "type":{
         "name":"Column"
      },
      "attributes":{
         "Data Type":[
            {
               "value":"object"
            }
         ]
      },
      "relations":{
         "00000000-0000-0000-0000-000000007042:TARGET":[
            {
               "name":"v1GetWeatherActualsData",
               "domain":{
                  "name":"enterprise-weather-data-product-api-sbx",
                  "community":{
                     "name":"APIs"
                  }
               }
            }
         ]
      }
   },
   {
      "resourceType":"Asset",
      "identifier":{
         "name":"v1GetWeatherActualsData",
         "domain":{
            "name":"enterprise-weather-data-product-api-sbx",
            "community":{
               "name":"APIs"
            }
         }
      },
      "type":{
         "name":"Table"
      },
      "relations":{
         "018da964-d53a-7b18-a8c8-044dbd47a622:SOURCE":[
            {
               "name":"GET /weather/actuals",
               "domain":{
                  "name":"enterprise-weather-data-product-api-sbx",
                  "community":{
                     "name":"APIs"
                  }
               }
            }
         ],
         "00000000-0000-0000-0000-000000007042:SOURCE":[
            {
               "name":"v1GetWeatherActualsData > starttime",
               "domain":{
                  "name":"enterprise-weather-data-product-api-sbx",
                  "community":{
                     "name":"APIs"
                  }
               }
            },
            {
               "name":"v1GetWeatherActualsData > endtime",
               "domain":{
                  "name":"enterprise-weather-data-product-api-sbx",
                  "community":{
                     "name":"APIs"
                  }
               }
            },
            {
               "name":"v1GetWeatherActualsData > provider",
               "domain":{
                  "name":"enterprise-weather-data-product-api-sbx",
                  "community":{
                     "name":"APIs"
                  }
               }
            },
            {
               "name":"v1GetWeatherActualsData > location",
               "domain":{
                  "name":"enterprise-weather-data-product-api-sbx",
                  "community":{
                     "name":"APIs"
                  }
               }
            }
         ]
      }
   },
   {
      "resourceType":"Asset",
      "identifier":{
         "name":"GET /weather/forecast/by_station",
         "domain":{
            "name":"enterprise-weather-data-product-api-sbx",
            "community":{
               "name":"APIs"
            }
         }
      },
      "type":{
         "name":"API Endpoint"
      },
      "relations":{
         "00000000-0000-0000-0000-000000007005:TARGET":[
            {
               "name":"enterprise-weather-data-product-api-sbx",
               "domain":{
                  "name":"enterprise-weather-data-product-api-sbx",
                  "community":{
                     "name":"APIs"
                  }
               }
            }
         ],
         "018da964-d53a-7b18-a8c8-044dbd47a622:TARGET":[
            {
               "name":"v1GetWeatherForecastByStation",
               "domain":{
                  "name":"enterprise-weather-data-product-api-sbx",
                  "community":{
                     "name":"APIs"
                  }
               }
            }
         ]
      }
   },
   {
      "resourceType":"Asset",
      "displayName":"inittime",
      "identifier":{
         "name":"v1GetWeatherForecastByStation > inittime",
         "domain":{
            "name":"enterprise-weather-data-product-api-sbx",
            "community":{
               "name":"APIs"
            }
         }
      },
      "type":{
         "name":"Column"
      },
      "attributes":{
         "Data Type":[
            {
               "value":"string"
            }
         ]
      },
      "relations":{
         "00000000-0000-0000-0000-000000007042:TARGET":[
            {
               "name":"v1GetWeatherForecastByStation",
               "domain":{
                  "name":"enterprise-weather-data-product-api-sbx",
                  "community":{
                     "name":"APIs"
                  }
               }
            }
         ]
      }
   },
   {
      "resourceType":"Asset",
      "displayName":"provider",
      "identifier":{
         "name":"v1GetWeatherForecastByStation > provider",
         "domain":{
            "name":"enterprise-weather-data-product-api-sbx",
            "community":{
               "name":"APIs"
            }
         }
      },
      "type":{
         "name":"Column"
      },
      "attributes":{
         "Data Type":[
            {
               "value":"string"
            }
         ]
      },
      "relations":{
         "00000000-0000-0000-0000-000000007042:TARGET":[
            {
               "name":"v1GetWeatherForecastByStation",
               "domain":{
                  "name":"enterprise-weather-data-product-api-sbx",
                  "community":{
                     "name":"APIs"
                  }
               }
            }
         ]
      }
   },
   {
      "resourceType":"Asset",
      "displayName":"data",
      "identifier":{
         "name":"v1GetWeatherForecastByStation > data",
         "domain":{
            "name":"enterprise-weather-data-product-api-sbx",
            "community":{
               "name":"APIs"
            }
         }
      },
      "type":{
         "name":"Column"
      },
      "attributes":{
         "Data Type":[
            {
               "value":"array"
            }
         ]
      },
      "relations":{
         "00000000-0000-0000-0000-000000007042:TARGET":[
            {
               "name":"v1GetWeatherForecastByStation",
               "domain":{
                  "name":"enterprise-weather-data-product-api-sbx",
                  "community":{
                     "name":"APIs"
                  }
               }
            }
         ]
      }
   },
   {
      "resourceType":"Asset",
      "identifier":{
         "name":"v1GetWeatherForecastByStation",
         "domain":{
            "name":"enterprise-weather-data-product-api-sbx",
            "community":{
               "name":"APIs"
            }
         }
      },
      "type":{
         "name":"Table"
      },
      "relations":{
         "018da964-d53a-7b18-a8c8-044dbd47a622:SOURCE":[
            {
               "name":"GET /weather/forecast/by_station",
               "domain":{
                  "name":"enterprise-weather-data-product-api-sbx",
                  "community":{
                     "name":"APIs"
                  }
               }
            }
         ],
         "00000000-0000-0000-0000-000000007042:SOURCE":[
            {
               "name":"v1GetWeatherForecastByStation > inittime",
               "domain":{
                  "name":"enterprise-weather-data-product-api-sbx",
                  "community":{
                     "name":"APIs"
                  }
               }
            },
            {
               "name":"v1GetWeatherForecastByStation > provider",
               "domain":{
                  "name":"enterprise-weather-data-product-api-sbx",
                  "community":{
                     "name":"APIs"
                  }
               }
            },
            {
               "name":"v1GetWeatherForecastByStation > data",
               "domain":{
                  "name":"enterprise-weather-data-product-api-sbx",
                  "community":{
                     "name":"APIs"
                  }
               }
            }
         ]
      }
   },
   {
      "resourceType":"Asset",
      "identifier":{
         "name":"GET /data/forecast",
         "domain":{
            "name":"enterprise-weather-data-product-api-sbx",
            "community":{
               "name":"APIs"
            }
         }
      },
      "type":{
         "name":"API Endpoint"
      },
      "relations":{
         "00000000-0000-0000-0000-000000007005:TARGET":[
            {
               "name":"enterprise-weather-data-product-api-sbx",
               "domain":{
                  "name":"enterprise-weather-data-product-api-sbx",
                  "community":{
                     "name":"APIs"
                  }
               }
            }
         ],
         "018da964-d53a-7b18-a8c8-044dbd47a622:TARGET":[
            {
               "name":"v1GetWeatherForecastData",
               "domain":{
                  "name":"enterprise-weather-data-product-api-sbx",
                  "community":{
                     "name":"APIs"
                  }
               }
            }
         ]
      }
   },
   {
      "resourceType":"Asset",
      "displayName":"inittime",
      "identifier":{
         "name":"v1GetWeatherForecastData > inittime",
         "domain":{
            "name":"enterprise-weather-data-product-api-sbx",
            "community":{
               "name":"APIs"
            }
         }
      },
      "type":{
         "name":"Column"
      },
      "attributes":{
         "Data Type":[
            {
               "value":"string"
            }
         ]
      },
      "relations":{
         "00000000-0000-0000-0000-000000007042:TARGET":[
            {
               "name":"v1GetWeatherForecastData",
               "domain":{
                  "name":"enterprise-weather-data-product-api-sbx",
                  "community":{
                     "name":"APIs"
                  }
               }
            }
         ]
      }
   },
   {
      "resourceType":"Asset",
      "displayName":"provider",
      "identifier":{
         "name":"v1GetWeatherForecastData > provider",
         "domain":{
            "name":"enterprise-weather-data-product-api-sbx",
            "community":{
               "name":"APIs"
            }
         }
      },
      "type":{
         "name":"Column"
      },
      "attributes":{
         "Data Type":[
            {
               "value":"string"
            }
         ]
      },
      "relations":{
         "00000000-0000-0000-0000-000000007042:TARGET":[
            {
               "name":"v1GetWeatherForecastData",
               "domain":{
                  "name":"enterprise-weather-data-product-api-sbx",
                  "community":{
                     "name":"APIs"
                  }
               }
            }
         ]
      }
   },
   {
      "resourceType":"Asset",
      "displayName":"data",
      "identifier":{
         "name":"v1GetWeatherForecastData > data",
         "domain":{
            "name":"enterprise-weather-data-product-api-sbx",
            "community":{
               "name":"APIs"
            }
         }
      },
      "type":{
         "name":"Column"
      },
      "attributes":{
         "Data Type":[
            {
               "value":"array"
            }
         ]
      },
      "relations":{
         "00000000-0000-0000-0000-000000007042:TARGET":[
            {
               "name":"v1GetWeatherForecastData",
               "domain":{
                  "name":"enterprise-weather-data-product-api-sbx",
                  "community":{
                     "name":"APIs"
                  }
               }
            }
         ]
      }
   },
   {
      "resourceType":"Asset",
      "identifier":{
         "name":"v1GetWeatherForecastData",
         "domain":{
            "name":"enterprise-weather-data-product-api-sbx",
            "community":{
               "name":"APIs"
            }
         }
      },
      "type":{
         "name":"Table"
      },
      "relations":{
         "018da964-d53a-7b18-a8c8-044dbd47a622:SOURCE":[
            {
               "name":"GET /data/forecast",
               "domain":{
                  "name":"enterprise-weather-data-product-api-sbx",
                  "community":{
                     "name":"APIs"
                  }
               }
            }
         ],
         "00000000-0000-0000-0000-000000007042:SOURCE":[
            {
               "name":"v1GetWeatherForecastData > inittime",
               "domain":{
                  "name":"enterprise-weather-data-product-api-sbx",
                  "community":{
                     "name":"APIs"
                  }
               }
            },
            {
               "name":"v1GetWeatherForecastData > provider",
               "domain":{
                  "name":"enterprise-weather-data-product-api-sbx",
                  "community":{
                     "name":"APIs"
                  }
               }
            },
            {
               "name":"v1GetWeatherForecastData > data",
               "domain":{
                  "name":"enterprise-weather-data-product-api-sbx",
                  "community":{
                     "name":"APIs"
                  }
               }
            }
         ]
      }
   },
   {
      "resourceType":"Asset",
      "identifier":{
         "name":"GET /test",
         "domain":{
            "name":"enterprise-weather-data-product-api-sbx",
            "community":{
               "name":"APIs"
            }
         }
      },
      "type":{
         "name":"API Endpoint"
      },
      "relations":{
         "00000000-0000-0000-0000-000000007005:TARGET":[
            {
               "name":"enterprise-weather-data-product-api-sbx",
               "domain":{
                  "name":"enterprise-weather-data-product-api-sbx",
                  "community":{
                     "name":"APIs"
                  }
               }
            }
         ],
         "018da964-d53a-7b18-a8c8-044dbd47a622:TARGET":[
            {
               "name":"ArrayOfTest",
               "domain":{
                  "name":"enterprise-weather-data-product-api-sbx",
                  "community":{
                     "name":"APIs"
                  }
               }
            }
         ]
      }
   },
   {
      "resourceType":"Asset",
      "displayName":"empty",
      "identifier":{
         "name":"ArrayOfTest > empty",
         "domain":{
            "name":"enterprise-weather-data-product-api-sbx",
            "community":{
               "name":"APIs"
            }
         }
      },
      "type":{
         "name":"Column"
      },
      "attributes":{
         "Data Type":[
            {
               "value":"array"
            }
         ]
      },
      "relations":{
         "00000000-0000-0000-0000-000000007042:TARGET":[
            {
               "name":"ArrayOfTest",
               "domain":{
                  "name":"enterprise-weather-data-product-api-sbx",
                  "community":{
                     "name":"APIs"
                  }
               }
            }
         ]
      }
   },
   {
      "resourceType":"Asset",
      "identifier":{
         "name":"ArrayOfTest",
         "domain":{
            "name":"enterprise-weather-data-product-api-sbx",
            "community":{
               "name":"APIs"
            }
         }
      },
      "type":{
         "name":"Table"
      },
      "relations":{
         "018da964-d53a-7b18-a8c8-044dbd47a622:SOURCE":[
            {
               "name":"GET /test",
               "domain":{
                  "name":"enterprise-weather-data-product-api-sbx",
                  "community":{
                     "name":"APIs"
                  }
               }
            }
         ],
         "00000000-0000-0000-0000-000000007042:SOURCE":[
            {
               "name":"ArrayOfTest > empty",
               "domain":{
                  "name":"enterprise-weather-data-product-api-sbx",
                  "community":{
                     "name":"APIs"
                  }
               }
            }
         ]
      }
   },
   {
      "resourceType":"Asset",
      "identifier":{
         "name":"GET /docs/{proxy}",
         "domain":{
            "name":"enterprise-weather-data-product-api-sbx",
            "community":{
               "name":"APIs"
            }
         }
      },
      "type":{
         "name":"API Endpoint"
      },
      "relations":{
         "00000000-0000-0000-0000-000000007005:TARGET":[
            {
               "name":"enterprise-weather-data-product-api-sbx",
               "domain":{
                  "name":"enterprise-weather-data-product-api-sbx",
                  "community":{
                     "name":"APIs"
                  }
               }
            }
         ],
         "018da964-d53a-7b18-a8c8-044dbd47a622:TARGET":[
            {
               "name":"empty",
               "domain":{
                  "name":"enterprise-weather-data-product-api-sbx",
                  "community":{
                     "name":"APIs"
                  }
               }
            }
         ]
      }
   },
   {
      "resourceType":"Asset",
      "identifier":{
         "name":"empty",
         "domain":{
            "name":"enterprise-weather-data-product-api-sbx",
            "community":{
               "name":"APIs"
            }
         }
      },
      "type":{
         "name":"Table"
      },
      "relations":{
         "018da964-d53a-7b18-a8c8-044dbd47a622:SOURCE":[
            {
               "name":"GET /docs/{proxy}",
               "domain":{
                  "name":"enterprise-weather-data-product-api-sbx",
                  "community":{
                     "name":"APIs"
                  }
               }
            }
         ],
         "00000000-0000-0000-0000-000000007042:SOURCE":[
            
         ]
      }
   },
   {
      "resourceType":"Asset",
      "identifier":{
         "name":"GET /docs",
         "domain":{
            "name":"enterprise-weather-data-product-api-sbx",
            "community":{
               "name":"APIs"
            }
         }
      },
      "type":{
         "name":"API Endpoint"
      },
      "relations":{
         "00000000-0000-0000-0000-000000007005:TARGET":[
            {
               "name":"enterprise-weather-data-product-api-sbx",
               "domain":{
                  "name":"enterprise-weather-data-product-api-sbx",
                  "community":{
                     "name":"APIs"
                  }
               }
            }
         ],
         "018da964-d53a-7b18-a8c8-044dbd47a622:TARGET":[
            {
               "name":"empty",
               "domain":{
                  "name":"enterprise-weather-data-product-api-sbx",
                  "community":{
                     "name":"APIs"
                  }
               }
            }
         ]
      }
   },
   {
      "resourceType":"Asset",
      "identifier":{
         "name":"empty",
         "domain":{
            "name":"enterprise-weather-data-product-api-sbx",
            "community":{
               "name":"APIs"
            }
         }
      },
      "type":{
         "name":"Table"
      },
      "relations":{
         "018da964-d53a-7b18-a8c8-044dbd47a622:SOURCE":[
            {
               "name":"GET /docs",
               "domain":{
                  "name":"enterprise-weather-data-product-api-sbx",
                  "community":{
                     "name":"APIs"
                  }
               }
            }
         ],
         "00000000-0000-0000-0000-000000007042:SOURCE":[
            
         ]
      }
   }
]
